name: Docker Build Test

on:
  pull_request:
    paths:
      - "**.py"
      - "uv.lock"
      - "pyproject.toml"
      - "Dockerfile"
      - ".python-version"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Log in to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Docker Image"
        run: |
          docker build .
